### ISSUE TITLE
Disable the Forums

### ISSUE THREAD

**Issue by raeleus** [libgdx/libgdx-site#44] opened 2020-02-17 16:30 UTC
**The state of affairs**
I have a great deal of time invested in the libGDX community. So when I make the following request, I do so with a tremendously heavy heart: the forums are overrun with bots and must be archived. The majority of posts are spam and bots responding to other bots. Nearly all regulars, contributors, and generally helpful people have moved on to other platforms. This is very discouraging to new users and regular users alike.

**Why not upgrade?**
It is clear that a forum upgrade should have happened a long time ago. The latest forum softwares are hardened against this kind of attack. No system is perfect, but it would be better than what we have to deal with right now. Nevertheless, this hasn't happened. I don't care to speculate as to why. I just know that it isn't going to happen in any reasonable time frame. I can also imagine the difficulty and time it would take to make such an upgrade which the libGDX team cannot afford.

**Why archive?**
There are many useful and historical posts in the forum that need to be preserved for future reference. These include posts by the libGDX team and fixes to unusual circumstances. These come up in search engine results all the time and are important to keep the library relevant.

**The proposal**
I suggest that the libgdx.com site removes the direct link to the forum. Users will be able to get support from the libGDX subreddit and Discord where we enjoy a bot free environment and an active community. The forum should lock creation of new accounts and block new posts. A disclaimer in the forum directing users to these other avenues for community will be placed plainly at the top of the page to explain the change.

Thank you for your time. The community is still alive and well! We would love to see this change happen to keep libGDX relevant and eliminate confusion/discouragement.

**Comment by badlogic** [comment] 2020-02-17 17:45
Yeah, that's not good. The problem is that I have no time to clean it up. Nor upgrade. It's all kept together with bubble gum and duct tape. I'm happy to link to a new place from the new site if someone wants to set something up. But I'm afraid I can't commit to upgrade the existing forum.

**Comment by cypherdare** [comment] 2020-02-17 18:00
I would vote for giving EvilEnity a chance to do a last pass cleanup, then making it read-only. On the website page about Community, mark the link as the “Archived forum”. I don’t know if the Discord channel is “official”, but it should be linked as an official community because it is quite active. And we can direct people to the StackOverflow `libgdx` tag as well.

**Comment by raeleus** [comment] 2020-02-18 02:11
I've consulted my colleagues and no one seems enthused about starting another forum, Badlogic. I agree with Cypherdare's idea of marking the existing link as Archived Forum. Links for [Stackoverflow](https://stackoverflow.com/tags/libgdx), [Discord](https://discord.gg/7c6Wg8H), and the [libGDX Reddit](https://www.reddit.com/r/libgdx/) should be sufficient. It is a very modern approach to managing a community if you look at Blender's [community page](https://www.blender.org/community/). They don't host their own forums.

**Comment by NathanSweet** [comment] 2020-02-22 15:44
Alright, I've configured the forum to disallow posting new topics, replying, editing, and deleting for registered users. I updated the [global post](https://www.badlogicgames.com/forum/viewtopic.php?f=11&t=6096) to explain the forum is archived and to point people other places. Can someone fix up the website?

**Comment by piotr-j** [comment] 2020-02-22 18:54
Are these links on first line in global post supposed to look like that?

**Comment by NathanSweet** [comment] 2020-02-23 15:53
Oops, fixed!

**Comment by rafaskb** [comment] 2020-02-23 19:20
The "Getting started" link is broken by the way. Changing the link to `https://libgdx.badlogicgames.com/documentation/` will fix the issue.

**Comment by NathanSweet** [comment] 2020-02-23 23:47
Fixed!

**Comment by mgsx-dev** [comment] 2020-04-22 08:07
https://libgdx.badlogicgames.com/community.html forum section needs an update :-)

**Comment by NathanSweet** [comment] 2020-04-23 22:44
Can someone handle that

**Comment by danpierzchala** [comment] 2020-05-02 20:09
Opened a PR to update the community page: https://github.com/libgdx/libgdx-site/pull/47

**Comment by crykn** [comment] 2020-08-28 15:39
The forums are disabled. Closing this.

**Closed by crykn** 2020-08-28 15:39 UTC
